[project]
name = "fast-ai-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastai>=2.8.2",
    "ipykernel>=6.29.5",
]
